FROM ruby:3.1.0

EXPOSE 3000

WORKDIR /usr/src/app

# Install the corret bundler version
RUN gem install bundler:2.3.3

# Copy the required files for dependencies to be installed
COPY Gemfile* ./

# Install dependencies
RUN bundle install

# Copy all the source code
COPY . . 

# The production mode is picked since we have no intention to run this in development mode
RUN rails db:migrate RAILS_ENV=production

RUN rake assets:precompile 

CMD ["rails", "s", "-e", "production"] 
