FROM nginx:alpine

RUN apk add --no-cache python3 py3-markdown

WORKDIR /usr/share/nginx/html

COPY README.md .

RUN markdown_py README.md > index.html
 
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

